                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                       
System.out.println("AAA                                         tttt            iiii                                                    BBBBBBBBBBBBBBBBB                                              tttt                                                           d::::::d                222222222222222                           000000000     ");
System.out.println("A:::A                                     ttt:::t           i::::i                                                   B::::::::::::::::B                                          ttt:::t                                                           d::::::d               2:::::::::::::::22                       00:::::::::00  "); 
System.out.println("A:::::A                                    t:::::t            iiii                                                    B::::::BBBBBB:::::B                                         t:::::t                                                           d::::::d               2::::::222222:::::2                    00:::::::::::::00"); 
System.out.println("A:::::::A                                   t:::::t                                                                    BB:::::B     B:::::B                                        t:::::t                                                           d:::::d                2222222     2:::::2                   0:::::::000:::::::0");
System.out.println("A:::::::::A            ccccccccccccccccttttttt:::::ttttttt    iiiiiii    ooooooooooo   nnnn  nnnnnnnn                     B::::B     B:::::B  aaaaaaaaaaaaa      ssssssssss   ttttttt:::::ttttttt      aaaaaaaaaaaaa  rrrrr   rrrrrrrrr       ddddddddd:::::d                            2:::::2                   0::::::0   0::::::0");
System.out.println("A:::::A:::::A         cc:::::::::::::::ct:::::::::::::::::t    i:::::i  oo:::::::::::oo n:::nn::::::::nn                   B::::B     B:::::B  a::::::::::::a   ss::::::::::s  t:::::::::::::::::t      a::::::::::::a r::::rrr:::::::::r    dd::::::::::::::d                            2:::::2                   0:::::0     0:::::0");
System.out.println("A:::::A A:::::A       c:::::::::::::::::ct:::::::::::::::::t     i::::i o:::::::::::::::on::::::::::::::nn                  B::::BBBBBB:::::B   aaaaaaaaa:::::ass:::::::::::::s t:::::::::::::::::t      aaaaaaaaa:::::ar:::::::::::::::::r  d::::::::::::::::d                         2222::::2                    0:::::0     0:::::0");
System.out.println("A:::::A   A:::::A     c:::::::cccccc:::::ctttttt:::::::tttttt     i::::i o:::::ooooo:::::onn:::::::::::::::n                 B:::::::::::::BB             a::::as::::::ssss:::::stttttt:::::::tttttt               a::::arr::::::rrrrr::::::rd:::::::ddddd:::::d                    22222::::::22                     0:::::0 000 0:::::0");
System.out.println("A:::::A     A:::::A    c::::::c     ccccccc      t:::::t           i::::i o::::o     o::::o  n:::::nnnn:::::n                 B::::BBBBBB:::::B     aaaaaaa:::::a s:::::s  ssssss       t:::::t              aaaaaaa:::::a r:::::r     r:::::rd::::::d    d:::::d                  22::::::::222                       0:::::0 000 0:::::0");
System.out.println("A:::::AAAAAAAAA:::::A   c:::::c                   t:::::t           i::::i o::::o     o::::o  n::::n    n::::n                 B::::B     B:::::B  aa::::::::::::a   s::::::s            t:::::t            aa::::::::::::a r:::::r     rrrrrrrd:::::d     d:::::d                 2:::::22222                          0:::::0     0:::::0");
System.out.println("A:::::::::::::::::::::A  c:::::c                   t:::::t           i::::i o::::o     o::::o  n::::n    n::::n                 B::::B     B:::::B a::::aaaa::::::a      s::::::s         t:::::t           a::::aaaa::::::a r:::::r            d:::::d     d:::::d                2:::::2                               0:::::0     0:::::0");
System.out.println("A:::::AAAAAAAAAAAAA:::::A c::::::c     ccccccc      t:::::t    tttttt i::::i o::::o     o::::o  n::::n    n::::n                 B::::B     B:::::Ba::::a    a:::::assssss   s:::::s       t:::::t    tttttta::::a    a:::::a r:::::r            d:::::d     d:::::d                2:::::2                               0::::::0   0::::::0");
System.out.println("A:::::A             A:::::Ac:::::::cccccc:::::c      t::::::tttt:::::ti::::::io:::::ooooo:::::o  n::::n    n::::n               BB:::::BBBBBB::::::Ba::::a    a:::::as:::::ssss::::::s      t::::::tttt:::::ta::::a    a:::::a r:::::r            d::::::ddddd::::::dd               2:::::2       222222                  0:::::::000:::::::0");
System.out.println("  A:::::A               A:::::Ac:::::::::::::::::c      tt::::::::::::::ti::::::io:::::::::::::::o  n::::n    n::::n               B:::::::::::::::::B a:::::aaaa::::::as::::::::::::::s       tt::::::::::::::ta:::::aaaa::::::a r:::::r             d:::::::::::::::::d               2::::::2222222:::::2      ......       00:::::::::::::00"); 
System.out.println("A:::::A                 A:::::Acc:::::::::::::::c        tt:::::::::::tti::::::i oo:::::::::::oo   n::::n    n::::n               B::::::::::::::::B   a::::::::::aa:::as:::::::::::ss          tt:::::::::::tt a::::::::::aa:::ar:::::r              d:::::::::ddd::::d               2::::::::::::::::::2      .::::.         00:::::::::00   ");
System.out.println("AAAAAAA                   AAAAAAA cccccccccccccccc          ttttttttttt  iiiiiiii   ooooooooooo     nnnnnn    nnnnnn               BBBBBBBBBBBBBBBBB     aaaaaaaaaa  aaaa sssssssssss              ttttttttttt    aaaaaaaaaa  aaaarrrrrrr               ddddddddd   ddddd               22222222222222222222      ......           000000000     ");
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                 